---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankingms
spec:
  selector:
    matchLabels:
      app: bankingms
  template:
    metadata:
      labels:
        app: bankingms
    spec:
      containers:
      - name: bankingms
        image: rahulkohli/core_banking_ms
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
