apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1.12-debian-kafka2-1
          env:
            - name: "FLUENT_KAFKA_BROKERS"
              value: "my-cluster-kafka-bootstrap.default.svc:9092"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: config-volume
              mountPath: /fluentd/etc
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config-volume
          configMap:
            name: fluentd-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
    version: v1
data:
  fluent.conf: |-
    @include fluent-source.conf
    @include fluent-filter.conf
    @include fluent-match.conf
  fluent-source.conf: |-
    <source>
      @type tail
      read_from_head true
      tag "kubernetes.*"
      path "/var/log/containers/**bankingms**.log"
      pos_file "/var/log/kubernetes.log.pos"
      <parse>
        @type kubernetes
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

  fluent-filter.conf: |-
    <filter kubernetes.**bankingms**.log>
      @type grep

      <regexp>
        key level
        pattern /[1-9]\d*/
      </regexp>

    </filter>
  fluent-match.conf: |-
    # Ignore fluentd logs
    <match kubernetes.var.log.containers.**fluentd**.log>
      @type null
    </match>
    # Ignore kube-system logs
    <match kubernetes.var.log.containers.**kube-system**.log>
      @type null
    </match>
    
    <match kubernetes.**bankingms**.log>
      @type kafka2

      brokers my-cluster-kafka-bootstrap.default.svc:9092

      <buffer topic>
        flush_mode immediate
        #flush_interval 2s
      </buffer>

      topic_key my-topic
      default_topic my-topic

      <format>
        @type json
      </format>

    </match>