---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loggingms
spec:
  selector:
    matchLabels:
      app: loggingms
  template:
    metadata:
      labels:
        app: loggingms
    spec:
      containers:
      - name: loggingms
        image: rahulkohli/logging-microservice
        env:
          - name: INFO_LOG_TOPIC
            value: my-topic
          - name: DATABASE_HOST
            value: mongo
          - name: DATABASE_PORT
            value: '27017'
          - name: DATABASE_NAME
            value: logs
          - name: DEBUG_LOG_TOPIC
            value: debug-log
          - name: ERROR_LOG_TOPIC
            value: error-log
          - name: VERBOSE_LOG_TOPIC
            value: verbose-log
          - name: FATAL_LOG_TOPIC
            value: fatal-log
          - name: KAFKA_BROKERS
            value: my-cluster-kafka-bootstrap.default.svc:9092
          - name: CONSUMER_GROUP_ID
            value: my-kafka-cluster
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
      volumes:
      - name: logging-config
        configMap:
          name: logging-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-config
  labels:
    app: loggingms
data:
  .env: |-
    DATABASE_HOST=mongo
    DATABASE_PORT=27017
    DATABASE_NAME=logs
    INFO_LOG_TOPIC=my-topic
    DEBUG_LOG_TOPIC=debug-log
    ERROR_LOG_TOPIC=error-log
    VERBOSE_LOG_TOPIC=verbose-log
    FATAL_LOG_TOPIC=fatal-log
    KAFKA_BROKERS=my-cluster-kafka-bootstrap.default.svc:9092
